### ISSUE TITLE
Leftover earbuds

### ISSUE THREAD

**Issue by fbottarel** [vvv-school/vvv18#54]
Someone left a pair of black earbuds in the conference room. Come get'em!

**Comment by traversaro** [comment]
cc @vvv-school/vvv18-students  @vvv-school/vvv18-teachers

**Comment by osm3000** [comment]
Thanks, it is mine
Maybe you can leave it at the reception for room 255. My roommate is still
there

On Feb 16, 2018 10:15 AM, "Silvio Traversaro" <notifications@github.com>
wrote:

cc @vvv-school/vvv18-students
<https://github.com/orgs/vvv-school/teams/vvv18-students>
@vvv-school/vvv18-teachers
<https://github.com/orgs/vvv-school/teams/vvv18-teachers>

—
You are receiving this because you are on a team that was mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/vvv-school/vvv18/issues/54#issuecomment-366181784>, or mute
the thread

**Comment by osm3000** [comment]
If not possible or you already left, it is not a problem ☺

**Comment by kosenhitatchi** [comment]
I'm almost leaving. Where are they?

**Comment by kosenhitatchi** [comment]
@fbottarel Where did you droped them?

**Comment by fbottarel** [comment]
Conference room

**Comment by kosenhitatchi** [comment]
@fbottarel  I went to the room and at the réception. Nothing is there. Sorry @osm3000

**Comment by kosenhitatchi** [comment]
I got them :-)
